// Generated by CoffeeScript 1.3.3

exports.init = function(root, config) {
  return {
    name: 'Angular.js',
    process: function(template, path, id) {
      return '<script type="text/ng-template" id="' + id + '.html">' + template + '</script>';
    }
  };
};
