// Generated by CoffeeScript 1.3.3

exports.process = function(program) {
  switch (program.args[0]) {
    case 'new':
    case 'n':
      return require('./generate').generate(program);
    default:
      return console.log('Type "socketstream new <projectname>" to create a new application');
  }
};
