// Generated by CoffeeScript 1.3.3

exports.process = function(program) {
  switch (program.args[0]) {
    case 'new':
    case 'n':
      if (!program.minimal) {
        program.stylus = true;
        program.hogan = true;
        program.jade = true;
      }
      return require('./generate').generate(program);
    default:
      return console.log('Type "socketstream new <projectname>" to create a new application');
  }
};
