// Generated by CoffeeScript 1.3.3
var cache, fs, http, pathlib, res, view;

fs = require('fs');

pathlib = require('path');

http = require('http');

view = require('./view');

cache = {};

res = http.ServerResponse.prototype;

module.exports = function(ss, clients, options) {
  res.serveClient = function(name) {
    var client, fileName, self, sendHTML;
    self = this;
    sendHTML = function(html) {
      self.writeHead(200, {
        'Content-Length': Buffer.byteLength(html),
        'Content-Type': 'text/html'
      });
      return self.end(html);
    };
    client = typeof name === 'string' && clients[name];
    if (client == null) {
      throw new Error('Unable to find single-page client: ' + name);
    }
    if (options.packedAssets) {
      if (!cache[name]) {
        fileName = pathlib.join(ss.root, options.dirs.assets, client.name, client.id + '.html');
        cache[name] = fs.readFileSync(fileName, 'utf8');
      }
      return sendHTML(cache[name]);
    } else {
      return view(ss, client, options, sendHTML);
    }
  };
  return res.serve = res.serveClient;
};
