// Generated by CoffeeScript 1.3.3

module.exports = function() {
  var config, transport;
  transport = null;
  config = {};
  return {
    use: function(nameOrModule, cfg) {
      var modPath;
      if (cfg == null) {
        cfg = {};
      }
      config = cfg;
      return transport = (function() {
        if (typeof nameOrModule === 'function') {
          return nameOrModule;
        } else {
          modPath = "./transports/" + nameOrModule;
          if (require.resolve(modPath)) {
            return require(modPath);
          } else {
            throw new Error("Unable to find Publish Event Transport '" + nameOrModule + "' internally. Please pass a module");
          }
        }
      })();
    },
    load: function() {
      if (transport == null) {
        this.use('internal');
      }
      return transport(config);
    }
  };
};
