// Generated by CoffeeScript 1.3.3
var apiTree, pathlib,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

pathlib = require('path');

apiTree = require('apitree');

exports.loadApiTree = function(dir) {
  var allowedExtensions, k, v;
  allowedExtensions = (function() {
    var _ref, _results;
    _ref = require.extensions;
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      if (k !== '.json') {
        _results.push(k);
      }
    }
    return _results;
  })();
  return apiTree.createApiTree(dir, {
    filter: function(name, names) {
      var ext, _ref;
      ext = pathlib.extname(name);
      return ext === '.js' || (__indexOf.call(allowedExtensions, ext) >= 0 && !(_ref = pathlib.basename(name, ext).concat('.js'), __indexOf.call(names, _ref) >= 0));
    }
  });
};
