// Generated by CoffeeScript 1.3.3
var EventEmitter2, ss;

EventEmitter2 = require('eventemitter2').EventEmitter2;

ss = require('socketstream');

module.exports = function(responderId, config, send) {
  var EE2;
  EE2 = new EventEmitter2;
  ss.registerApi('event', EE2);
  return ss.message.on(responderId, function(msg, meta) {
    var args, ee, obj;
    obj = JSON.parse(msg);
    args = [obj.e];
    args = args.concat(obj.p);
    (meta != null) && args.push(meta);
    ee = obj.e && obj.e.substr(0, 5) === '__ss:' && ss.server || EE2;
    return ee.emit.apply(ee, args);
  });
};
