// Generated by CoffeeScript 1.3.3
var apiTree, existslib, pathlib;

pathlib = require('path');

existslib = process.version.split('.')[1] === '6' && require('path') || require('fs');

apiTree = require('apitree');

module.exports = function(ss, config) {
  var customDir, internal;
  customDir = pathlib.join(ss.root, 'server/middleware');
  internal = require('./internal')(ss);
  return {
    load: function() {
      var k, stack, v;
      stack = existslib.existsSync(customDir) && apiTree.createApiTree(customDir) || {};
      for (k in internal) {
        v = internal[k];
        stack[k] = v;
      }
      return stack;
    }
  };
};
